# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AVC.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from qtvcp.widgets.hal_label import HALLabel
from qtvcp.widgets.simple_widgets import DoubleScale, PushButton

class UI_AVC(QtWidgets.QWidget):
    def __init__(self):
        super(UI_AVC, self).__init__()
        # Carrega a interface a partir do arquivo .ui
        uic.loadUi("AVC.ui", self)
        # Agora você pode acessar os widgets definidos no .ui, 
        # por exemplo, se houver um botão com objectName "meuBotao":
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AVC = UI_AVC()
    AVC.show()
    win_id = int(AVC.winId())
    print(win_id, flush=True)
    sys.exit(app.exec_())
    
